WIP: Migration Proof of Concept
kwrooijen/gungnir pull request #13
Opened 2020-08-23 21:07 UTC by ma-Rac

Don't merge, it's just a proof of concept to test out ideas.

It tried to recreate the conditions laid out in #2 

The first migration wasn't possible, I had an issue with loading ossp-uuid, something about versions being different, but I tested and the [:raw] tag works as expected.

The second migration was slightly adapted for 2 reasons: 
1) postgres doesn't like making a user table (i mean you can make it but it's going to be annoying because you always have to have it in quotations)

2) the :table.add/column key was changed to just table/column, so it more closely resembles the protocol used in [honeysql-postgres](https://github.com/nilenso/honeysql-postgres#create-table)

I added a small folder with the migrations in a mostly random location

to test the existing migrations out:
- make sure gungnir.database/*datasource* has been defined,
- run `(gungnir.database/make-datasource! with-valid-arguments)`
- run `(gungnir.migration/migrate-all)`

to test creating a migration use `(gungnir.migration/create-migration name content)`

2020-08-23 21:33 UTC, kwrooijen requested changes
Very cool! I added a few comments that you can work on / think about. I haven't looked deeply in the details yet. I'll have more time in the evening tomorrow.

2020-08-23 21:33 UTC, kwrooijen commented on src/clj/gungnir/migration.clj
> +    [raw-sql]))
Might want to do a `string/join "\n" raw-sqls` here. That way each string will be a new line. Making it easier to format

2020-08-23 21:33 UTC, kwrooijen commented on gungnir/migrations/20200820174119-allow-uuids.edn
> +{:up [:raw ""]
These are useful for the draft, but also for testing. Might be a good idea to move in the test directory

2020-08-23 21:33 UTC, kwrooijen commented on gungnir/migrations/20200820204015-remove-user-email-add-password.edn
> +  [:table.add/column {:type :text} "email"]]}
An idea, maybe support `:size` for type `:test` ?

2020-08-23 21:33 UTC, kwrooijen commented on src/clj/gungnir/migration.clj
> +
General note: Can you move any "helper" functions to the top, and mark them as private? Any multimethods underneath the private, and any publics underneath that. That will help unclutter everything a bit (even though this is just a draft, it will still be helpful)

2020-08-23 21:33 UTC, kwrooijen commented on gungnir/migrations/20200820203744-add-user-table.edn
> + [:table/create "users"
Something to think about: What if we want to apply multiple changes in an `:up` or `:down` stage? Right now we can only apply 1 change. Nested vector maybe?

2020-08-23 21:33 UTC, kwrooijen commented on src/clj/gungnir/migration.clj
> +
Also add a docstring with `"TODO"` to any public functions / multimethods. We don't have to write the docstrings right away since the API might change. But it's so we don't forget afterwards

2020-08-23 21:33 UTC, kwrooijen commented on src/clj/gungnir/migration.clj
> +(defn create-migration
I guess this would be useful for a `lein` plugin? Or is this more meant for testing?

2020-08-23 21:36 UTC, kwrooijen commented
Gungnir now also supports mutliple datasources. So we shouldn't forget to also support that.

2020-08-24 11:33 UTC, ma-Rac commented on gungnir/migrations/20200820204015-remove-user-email-add-password.edn
> +  [:table.add/column {:type :text} "email"]]}
I suppose that was meant to be `:text` , 
and yeah there's an inline comment referring to datatypes that require an argument.
`(;NOTE this should be (apply sql/call (:type options)) if it's an seq, for data types like varchar that need a parameter (varchar(5)))`

My suggestion is that for such datatypes we should pass the value of `:type` as a seq with the type name as the first entry and parameters as the remaining ones, for example:

```clojure
[table.add/column {:type [:text 40]} "message"]
```

2020-08-24 11:34 UTC, ma-Rac commented on src/clj/gungnir/migration.clj
> +
Will do, also need to add specs for the public functions as well, eventually.

2020-08-24 11:39 UTC, ma-Rac commented on gungnir/migrations/20200820203744-add-user-table.edn
> + [:table/create "users"
Hmm... yeah I guess we could easily add a key for that something like:

```clojure
{:up [:sql/sequence
          [:table/create "pancakes"
            [:table/column {:type :intger} "score"]
            [:table/column {:type :text} "description"]]
          [:table/drop "waffles"]]}

```

2020-08-24 11:44 UTC, ma-Rac commented on src/clj/gungnir/migration.clj
> +(defn create-migration
ah yeah this was made because:
 - it makes it easier to add the "make migration from model" behaviour
 - potentially useful to make lein plugins
 - and because the id used for migrations is actually a timestamp (this is behaviour I copied from rails because when you have just an increasing sequence and multiple developers working on the same project if 2 people make migrations they always have to go and fix the numbering when most of the time it makes no difference which goes first), and manually adding a timestamp is tedious.

2020-08-24 19:06 UTC, kwrooijen commented
> the :table.add/column key was changed to just table/column, so it more closely resembles the protocol used in honeysql-postgres
I don't think we need to adhere to honeysql-postgres to be honest. If we call adding a column `:table/column`, what do we call removing a column? Also I don't see `:table/column` in honeysql-postgres.I see `add-column` and `drop-column` though.

Another option is:

`:table/add`
`:table/remove`
`:table/modify`

`:column/add`
`:column/remove`
`:column/modify`

The most important thing is that we're consistent and clear

2020-08-24 19:14 UTC, ma-Rac commented
Hmm.. the issue I had with that is that `:table.add/column` is processed differently when it's inside of `:table/create` and `:table/modify`.

since it's inside a `:table/create` clause the only action available is to add columns, and I thought that it made sense that the arguments are `:table/column`s they are just entities that represent a column in a table.

Create table sql example (note that it's passed as parameters to the create table clause):

```sql
CREATE TABLE films (
    code        char(5) CONSTRAINT firstkey PRIMARY KEY,
    title       varchar(40) NOT NULL,
    did         integer NOT NULL,
    date_prod   date,
    kind        varchar(10),
    len         interval hour to minute
);
```

Alter table example: 

```sql
ALTER TABLE distributors 
      ADD COLUMN address varchar(30),
      DROP COLUMN password;
```

2020-08-24 19:37 UTC, kwrooijen commented
Right. that makes sense. What we could do is this: Currently you have a single multi method for everything. Instead why not create a single mutlimethod for the tables, and a multimethod per context for the fields? A context being either `:table/add` `:table/modify` and `:table/remove`. Here's how I imagine it (note this is just sketched out code):


```clojure
{:up
 [:table/add {:table "users"}
  [:column/add {:primary-key true :type :uuid} "id"]
  [:column/add {:type :text} "email"]]
 :down
 [:table/remove {:table "users"}]}

{:up
 [:table/modify {:table "users"}
  [:column/modify {:type :integer} "email"]
  [:column/add {:type :text} "password"]]
 :down
 [:table/modify {:table "users"}
  [:column/modify {:type :text} "email"]
  [:column/remove "password"]]}

;; Multimethod per context (we don't need one for `:table/remove` since it won't change fields.
;; The identifier for these keys is a tuple with the action (`:column/add` or `:column/remove`). And the `:type`
;; This way we can extend new types, for each context, and each action, cleanly separated.

(defmulti process-field-add (fn [_m [k opts _column]] [k (:type opts)]))
(defmulti process-field-modify (fn [_m [k opts _column]] [k (:type opts)]))

;;
;; TABLE/ADD FIELDS
;;
(defmethod process-field-add [:column/add :uuid] [m [_ opts column]]
  ;; Here we modify `m` to add a UUID column with name `column`
  )

(defmethod process-field-add [:column/add :text] [m [_ opts column]]
  ;; Here we modify `m` to add a text column with name `column`,
  ;; optionally :size in `opts'
  )

;;
;; TABLE/MODIFY FIELDS
;;
(defmethod process-field-modify [:column/add :uuid] [m [_ opts column]]
  ;; Here we modify `m` to add a UUID column with name `column`
  )
(defmethod process-field-modify [:column/add :text] [m [_ opts column]]
  ;; Here we modify `m` to add a text column with name `column`,
  ;; optionally :size in `opts'
  )

(defmulti process-action first)

(defmethod process-action :table/add [[_ opts & fields]]
  (reduce process-field-add {} fields))

(defmethod process-action :table/modify [[_ opts & fields]]
  (reduce process-field-modify {} fields))
```

Does this make sense?

2020-08-24 19:41 UTC, kwrooijen commented on gungnir/migrations/20200820204015-remove-user-email-add-password.edn
> +  [:table.add/column {:type :text} "email"]]}
I think it would be better to do `{:type :text :size 40}`, that way we can extend it (e.g. what if we want to add a default? Would we have to place these in the correct order?)

2020-08-24 20:03 UTC, ma-Rac commented
Aaaaaaahhh decomplecting the processing into it's specific multi-method, smart. Though I don't understand the point of checking the type of the column in the dispatch function, I guess it does separate it even more, but then we're taking on some of the weight that could be lifted by the honeysql libraries.

Are there fields that take parameters optionally? I'm not good enough at pure sql to know that. 
If there are then it might be one more conditional.

I'll try it out and see if it has any practical annoyances that I can't work out!

2020-08-24 20:10 UTC, ma-Rac commented on src/clj/gungnir/migration.clj
> +(defn create-migration
I currently run it from the repl, and it's easier than writing the file-name by hand, since it's something you'd do while developing on the code-base it makes sense you'd have a repl open anyway.

2020-08-24 20:12 UTC, ma-Rac commented on gungnir/migrations/20200820204015-remove-user-email-add-password.edn
> +  [:table.add/column {:type :text} "email"]]}
I'm not even sure text even takes parameters, so your way makes sense, especially since we're probably going to change into 2 extensible multimethods anyway, which would also make them more overrideable too.

Will do!

2020-08-24 20:14 UTC, ma-Rac commented on gungnir/migrations/20200820204015-remove-user-email-add-password.edn
> +  [:table.add/column {:type :text} "email"]]}
Though the options map contains other keys, for stuff like primary-key, constraints, not null, etc. Should the key be namespaced to avoid ambiguity? so `{:type :text :type/size 40}`?

2020-08-24 20:26 UTC, kwrooijen commented
We could leave it to honeysql to figure out the type, but then we'd be stuck it with, without any flexibility. If we'd decide to support another database in the future we'd be in trouble. because our migration system is highly dependent on a honeysql compliant implementation to manage our types. I think we should use honeysql purely to generate correct SQL strings, but that's it. The less we rely on it the better imo

> Are there fields that take parameters optionally? 

You mean in the `opts` ? You could have `:default`, `:size`, `:primary-key`. Those are the ones I can think of from the top of my head.

Another thing is we need to be able to create indexes, e.g. `:index/add` (but let's leave that for phase 2). But indexes also have optional settings. e.g. the method (default `btree`)

2020-08-24 20:39 UTC, ma-Rac commented
I meant column datatypes, like varchar takes a parameter for length (e.g `varchar(20)`), but I don't know if there are column datatypes that take it optionally and have a default.

It's not very important, I'll proceed as suggested.

2021-01-19 22:46 UTC, kwrooijen commented
Closing in favor of https://github.com/kwrooijen/gungnir/pull/35

2021-01-19 22:46 UTC, closed without merging